### ISSUE TITLE
Development Installation

### ISSUE THREAD

**Issue by zhumingpassional** [MatProGo-dev/Gurobi.go#1] opened 2023-07-22 09:09 UTC
I follow the instructions:
Clone the library using git clone github.com/MatProGo-dev/Gurobi.go 
Run the setup script from inside the cloned repository: go generate.

after "go generate", there are the following :
warning: GOPATH set to GOROOT (/usr/local/go) has no effect
warning: GOPATH set to GOROOT (/usr/local/go) has no effect
gurobi1002
{/Library/gurobi100/mac64 gurobi/cgoHelper.go gurobi/gurobi_passthrough.h gurobi}
<nil>

then I go the folder "example", and run qp.go, and it raises errors:
command-line-arguments
/usr/local/go/pkg/tool/darwin_amd64/link: running clang failed: exit status 1
ld: warning: directory not found for option '-L/Library/gurobi100/mac64/lib'
ld: library not found for -lgurobi_c++
clang: error: linker command failed with exit code 1 (use -v to see invocation)

could you pls tell me the reason?

**Comment by kwesiRutledge** [comment] 2023-07-22 14:09
Hm. I have a couple of questions that will help me better understand your issue. Can you answer these:

1. What operating system are you using?
2. Did you run `go generate` only? Or did you also try `sudo go generate`? (Sometimes, the sudo is necessary in order to get proper access to the gurobi directory.)
3. It looks like you have Gurobi version 10.0.2 installed. Is that correct?
 
I think this library was made before 10.0.2 existed and I will need to adjust the setup script to handle this. You can see that it was designed for version numbers that could be expressed with only three digits (this is why it looks for the directory `-L/Library/gurobi100/mac64/lib` which ignores the last digit of 10.0.2). I will start on a fix soon.

**Comment by zhumingpassional** [comment] 2023-07-22 14:30
Thanks for your reply.

1. MacOS
2. I tried both "go generate" and "sudo go generate"
After I try "sudo go generate", the following exists:
gurobi1002
{/Library/gurobi100/mac64 gurobi/cgoHelper.go gurobi/gurobi_passthrough.h gurobi}
<nil>

Then I run qp.go, and it raises error:
command-line-arguments
/usr/local/go/pkg/tool/darwin_amd64/link: running clang failed: exit status 1
ld: warning: directory not found for option '-L/Library/gurobi100/mac64/lib'
ld: library not found for -lgurobi_c++
clang: error: linker command failed with exit code 1 (use -v to see invocation)

3. Yes.

**Comment by kwesiRutledge** [comment] 2023-07-22 15:19
I just merged a change that should fix your issue as well as give more verbose output during the `go generate` process. Please feel free to come back to this issue and reopen it if that fix doesn't work for you!

**Closed as completed by kwesiRutledge** 2023-07-22 15:19 UTC
